# to bind the Role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-rolebinding
subjects:
- kind: ServiceAccount
  name: default  # Replace with the name of your service account if it's different
  namespace: default
roleRef:
  kind: Role
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io
