apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-job-app
  labels:
    app: flask-job-app
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: flask-job-app
  template:
    metadata:
      labels:
        app: flask-job-app
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: flask-job-app
      # Add the local image name
        image: flask-job-app
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container
        - containerPort: 5000
